apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshoppublicapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshoppublicapi
  template:
    metadata:
      labels:
        app: eshoppublicapi
    spec:
      containers:
      - name: eshoppublicapi
        image: myaksclusteracr73043.azurecr.io/eshoppublicapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Docker"
        - name: ASPNETCORE_URLS
          value: "http://+:80"

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: eshoppublicapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eshoppublicapi
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---

apiVersion: v1
kind: Service
metadata:
  name: eshoppublicapi
spec:
  selector:
    app: eshoppublicapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
